BasicApp/urls.py
from django.conf.urls import url
from BasicApp import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$', views.SchoolListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='detail'),
    url(r'^create/$', views.SchoolCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='delete'),
]

ClassBasedViews/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from BasicApp import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view()),
    url(r'^basicapp/', include('BasicApp.urls', namespace="BasicApp")),
]

BasicApp/models.py
from django.db import models
from django.core.urlresolvers import reverse
# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk': self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students')

    def __str__(self):
        return self.name

BasicApp/views.py
from django.shortcuts import render
from django.views.generic import (View, TemplateView,
                                  ListView, DetailView,
                                  CreateView, UpdateView,
                                  DeleteView)
from . import models
from django.core.urlresolvers import reverse_lazy

class IndexView(TemplateView):
    template_name = 'index.html'


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'BasicApp/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

BasicApp/templates/BasicApp/BasicApp_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <ul class="nav navbar-nav">
        <li>
          <a class="navbar-brand" href="{% url 'basic_app:list'%}">Schools</a>
        </li>
        <li>
          <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li>
          <a href="#"></a>
        </li>
      </ul>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

BasicApp/templates/BasicApp/school_confirm_delete.html
{% extends "BasicApp/BasicApp_base.html" %}

{% block body_block %}
  <h1>Delete {{school.name}}?</h1>
  <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
  </form>
{% endblock %}

BasicApp/templates/BasicApp/school_detail.html
{% extends "BasicApp/BasicApp_base.html" %}

{% block body_block %}
  <div class="jumbotron">
    <h1>Welcome to the school detail page!</h1>
    <h2>School details: </h2>
    <p>Name: {{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal }}</p>
    <p>Location: {{school_detail.location }}</p>
    <h3>Students:</h3>
    {% for student in school_detail.students.all %}
      <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}
  </div>
  <div class="container">
    <p>
      <a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a>
    </p>

  </div>
{% endblock %}

BasicApp/templates/BasicApp/school_form.html
{% extends "BasicApp/BasicApp_base.html" %}

{% block body_block %}
  <h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
  </h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit">
  </form>
{% endblock %}

BasicApp/templates/BasicApp/school_list.html
{% extends "BasicApp/BasicApp_base.html" %}

{% block body_block %}
  <h1>Welcome to a list of all the schools!</h1>
  <ol>
    {% for school in schools %}
    <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
    {% endfor %}
  </ol>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title></title>
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <ul class="nav navbar-nav">
        <li>
          <a class="navbar-brand" href="{% url 'basic_app:list'%}">Schools</a>
        </li>
        <li>
          <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li>
          <a href="#"></a>
        </li>
      </ul>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block body_block %}
  <div class="jumbotron">
    <h1>Home page!</h1>
  </div>
{% endblock %}